export const MENU_ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/user/create",
    PASSWORD_REC: "/login/account-recovery",
    USER_PROFILE: "/profile",
    ADMIN_USER_PROFILE: "/admin/user-profile",
    CALENDAR: "/calendar",
    USERS_LIST: "/admin/users",
    USER_LOGOUT: "/logout",
    DELETE_USER: "/user/delete/",
    GET_USER: "/user/",
    GET_USER_PROFILE: "/user/",
    UPDATE_USER_PROFILE: "/user/update",
    NOT_FOUND: "/*",
    RECOVERY_PASSWORD: "/forgotPassword",
    RESET_PASSWORD: "/reset",
    UPDATE_PASSWORD: "/updatePasswordViaEmail",
    CHECK_DAY: "/reservations",
    BOOK_HOUR: "/reservation/create",
    LIST_USER_RESERVATION: '/reservations/',
    LIST_ADMIN_RESERVATION: '/allreservations',
    REGULATIONS: '/regulations',
    PRIZE_LIST: '/prizeList'
};
