export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOAD_USER = 'CHECK_USER';
export const CHECK_USER_FAIL = 'CHECK_USOS_USER_FAIL';

export const CHECK_USOS_USER_SUCCESS = 'CHECK_USOS_USER_SUCCESS';
export const AUTH_LOGOUT_USOS = 'AUTH_LOGOUT_USOS';

export const START_LOADING_USER = 'START_LOADING_USER';
export const END_LOADING_USER = 'END_LOADING_USER';

export const SWITCH_MODE_THEME = 'SWITCH_MODE_THEME';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const IS_EXIST_EMAIL = 'IS_EXIST_EMAIL';

export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS_LIST = 'CLEAR_USERS_LIST';
export const DELETE_USER = 'DELETE_USER';
export const GET_USER = 'GET_USER';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const CHANGE_AUTH_USER = 'CHANGE_AUTH_USER';

export const RECOVERY_PASSWORD_SUCCESS = 'RECOVERY_PASSWORD_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';

export const CHECK_DAY = 'CHECK_DAY';
export const CANCEL_DAY = 'CANCEL_DAY';
export const CHANGE_COURT = 'CHANGE_COURT';
export const ADD_NEW_RESERVATION = 'ADD_NEW_RESERVATION';

export const FETCH_LIST_RESERVATION_USER = 'FETCH_LIST_RESERVATION_USER';

export const ADD_RESERVATIONS_TO_LIST = 'ADD_RESERVATIONS_TO_LIST';
export const SEND_RESERVATION_LIST = 'SEND_RESERVATION_LIST';
export const DELETE_RESERVATION_LIST = 'DELETE_RESERVATION_LIST';
export const CLEAR_RESERVATION_LIST = 'CLEAR_RESERVATION_LIST';
export const SET_COURT_ID = 'SET_COURT_ID';

export const GET_PRICE_LIST = 'GET_PRICE_LIST';
export const GET_COURTS = 'GET_COURTS';
export const GET_PRICE = 'GET_PRICE';

export const GET_PAYU_TOKEN = 'GET_PAYU_TOKEN';
