export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOAD_USER = 'CHECK_USER';
export const CHECK_USER_FAIL = 'CHECK_USOS_USER_FAIL';

export const CHECK_USOS_USER_SUCCESS = 'CHECK_USOS_USER_SUCCESS';
export const AUTH_LOGOUT_USOS = 'AUTH_LOGOUT_USOS';

export const START_LOADING_USER = 'START_LOADING_USER';
export const END_LOADING_USER = 'END_LOADING_USER';

export const SWITCH_MODE_THEME = 'SWITCH_MODE_THEME';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const IS_EXIST_EMAIL = 'IS_EXIST_EMAIL';

export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS_LIST = 'CLEAR_USERS_LIST';
export const DELETE_USER = 'DELETE_USER';
export const GET_USER = 'GET_USER';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const CHANGE_AUTH_USER = 'CHANGE_AUTH_USER';
